styleguide: sourcelevel/linters
engines:
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: false
  bandit:
    enabled: true
  remark-lint:
    enabled: true
  duplication:
    enabled: true

exclude_paths:
  - tests
